services:
  cpp-app:
    build: .
    container_name: cpp-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
